// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://duyxlcqmpwisnmivvglg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR1eXhsY3FtcHdpc25taXZ2Z2xnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNzkyODYsImV4cCI6MjA2Mzk1NTI4Nn0.ODUKq5esdT3hYd7mm0Q9uQsbcQxo42aH7YrIzBNfHtI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);